use angelabible;

insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Gen',1,'创世纪 (Genesis)','','OT','五经律法书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Exod',2,'出埃及记 (Exodus)','','OT','五经律法书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Lev',3,'利未记 (Leviticus)','','OT','五经律法书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Num',4,'民数记 (Numbers)','','OT','五经律法书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Deut',5,'申命记 (Deuteronomy)','','OT','五经律法书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Josh',6,'约书亚记 (Joshua)','','OT','历史书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Judg',7,'士师记 (Judges)','','OT','历史书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Ruth',8,'路得记 (Ruth)','','OT','历史书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('1Sam',9,'撒母耳记上(1 Samuel)','','OT','历史书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('2Sam',10,'撒母耳记下(2 Samuel)','','OT','历史书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('1Kgs',11,'列王纪上(1 Kings)','','OT','历史书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('2Kgs',12,'列王纪下(2 Kings)','','OT','历史书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('1Chr',13,'历代志上(1 Chronicles)','','OT','历史书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('2Chr',14,'历代志下(2 Chronicles)','','OT','历史书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Ezra',15,'以斯拉记(Ezra)','','OT','历史书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Neh',16,'尼希米记(Nehemiah)','','OT','历史书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Esth',17,'以斯帖记 (Esther)','','OT','历史书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Job',18,'约伯记 (Job)','','OT','诗歌智慧书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Ps',19,'诗篇 (Psalms)','','OT','诗歌智慧书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Prov',20,'箴言 (Proverbs)','','OT','诗歌智慧书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Eccl',21,'传道书 (Ecclesiastes)','','OT','诗歌智慧书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Song',22,'雅歌 (Song of Songs)','','OT','诗歌智慧书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Isa',23,'以赛亚书 (Isaiah)','','OT','先知书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Jer',24,'耶利米书 (Jeremiahr)','','OT','先知书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Lam',25,'耶利米哀歌(Lamentations)','','OT','先知书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Ezek',26,'以西结书 (Ezekielk)','','OT','先知书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Dan',27,'但以理书 (Daniel)','','OT','先知书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Hos',28,'何西阿书 (Hosea)','','OT','先知书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Joel',29,'约珥书 (Joel)','','OT','先知书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Amos',30,'阿摩司书 (Amoss)','','OT','先知书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Obad',31,'俄巴底亚书 (Obadiah)','','OT','先知书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Jonah',32,'约拿书 (Jonah)','','OT','先知书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Mic',33,'弥迦书 (Micah)','','OT','先知书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Nah',34,'那鸿书 (Nahum)','','OT','先知书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Hab',35,'哈巴谷书 (Habakkuk)','','OT','先知书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Zeph',36,'西番雅书 (Zephaniah)','','OT','先知书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Hag',37,'哈该书 (Haggai)','','OT','先知书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Zech',38,'撒迦利亚书 (Zechariah)','','OT','先知书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Mal',39,'玛拉基书 (Malachi)','','OT','先知书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Matt',40,'马太福音 (Matthew)','','NT','福音书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Mark',41,'马可福音 (Mark)','','NT','福音书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Luke',42,'路加福音 (Luke)','','NT','福音书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('John',43,'约翰福音 (John)','','NT','福音书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Acts',44,'使徒行传 (Acts)','','NT','教会历史书')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Rom',45,'罗马书 (Romans, Rom)','','NT','保罗书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('1Cor',46,'哥林多前书 (1 Corinthians)','','NT','保罗书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('2Cor',47,'哥林多后书 (2 Corinthians)','','NT','保罗书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Gal',48,'加拉太书 (Galatians)','','NT','保罗书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Eph',49,'以弗所书 (Ephesus)','','NT','保罗书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Phil',50,'腓立比书 (Philippians)','','NT','保罗书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Col',51,'歌罗西书 (Colossians)','','NT','保罗书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('1Thess',52,'帖撒罗尼迦前书 (1 Thessalonians)','','NT','保罗书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('2Thess',53,'帖撒罗尼迦后书 (2 Thessalonians)','','NT','保罗书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('1Tim',54,'提摩太前书 (1 Timothy)','','NT','保罗书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('2Tim',55,'提摩太后书 (2 Timothy)','','NT','保罗书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Titus',56,'提多书 (Titus)','','NT','保罗书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Phlm',57,'腓利门书 (Philemon)','','NT','保罗书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Heb',58,'希伯来书 (Hebrews) ','','NT','普通书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Jas',59,'雅各书 (James)','','NT','普通书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('1Pet',60,'彼得前书(1 Peter)','','NT','普通书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('2Pet',61,'彼得后书(2 Peter)','','NT','普通书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('1John',62,'约翰一书(1 John)','','NT','普通书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('2John',63,'约翰二书(2 John)','','NT','普通书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('3John',64,'约翰三书(3 John)','','NT','普通书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Jude',65,'犹大书 (Jude)','','NT','普通书信')
insert into [dbo].[Book]([book],[index],[name],[describe],[treatment],[group]) values('Rev',66,'启示录 (Revelation)','','NT','启示录')